/* ======================================================================
   SCHOOL OF OLYMPIAD — MOCK DATA LAYER
   Structured to mirror a real relational schema (see /about#data-model
   in the build notes). Swap this file for API calls when a backend is
   connected — every page reads exclusively through the SOO.* accessors.
   ====================================================================== */

const SOO_SUBJECTS = [
  { slug:"mathematics", name:"Mathematics", short:"Math", icon:"sigma", color:"var(--sub-math)",
    desc:"Algebra, number theory, geometry and combinatorics for olympiad-style proof and problem solving.",
    topics:["Algebra","Number Theory","Geometry","Combinatorics","Inequalities","Functional Equations","Probability","Mathematical Proof","Advanced Problem Solving"],
    questionCount:2140, competitionCount:14 },
  { slug:"physics", name:"Physics", short:"Physics", icon:"atom", color:"var(--sub-physics)",
    desc:"Mechanics through modern physics, with a strong emphasis on experimental reasoning.",
    topics:["Mechanics","Electricity","Magnetism","Thermodynamics","Waves","Optics","Modern Physics","Relativity","Experimental Physics","Mathematical Methods"],
    questionCount:1870, competitionCount:11 },
  { slug:"chemistry", name:"Chemistry", short:"Chem", icon:"flask", color:"var(--sub-chem)",
    desc:"From reaction mechanisms to spectroscopy, chemical equilibrium and electrochemistry.",
    topics:["General Chemistry","Organic Chemistry","Inorganic Chemistry","Physical Chemistry","Analytical Chemistry","Biochemistry","Spectroscopy","Thermodynamics","Chemical Equilibrium","Electrochemistry"],
    questionCount:1610, competitionCount:9 },
  { slug:"biology", name:"Biology", short:"Bio", icon:"leaf", color:"var(--sub-bio)",
    desc:"Cell and molecular biology, genetics, physiology and ecology with lab-based reasoning.",
    topics:["Cell Biology","Molecular Biology","Genetics","Evolution","Ecology","Physiology","Biochemistry","Botany","Zoology","Experimental Biology"],
    questionCount:1930, competitionCount:10 },
  { slug:"computer-science", name:"Computer Science", short:"CS", icon:"code", color:"var(--sub-cs)",
    desc:"Algorithms, data structures and competitive programming, judged on real test cases.",
    topics:["Algorithms","Data Structures","Dynamic Programming","Graph Theory","Number Algorithms","Geometry","Strings","Greedy Algorithms","Computational Mathematics","Complexity"],
    questionCount:1480, competitionCount:8 },
  { slug:"astronomy", name:"Astronomy", short:"Astro", icon:"star", color:"var(--sub-astro)",
    desc:"Astrophysics, celestial mechanics and observational astronomy for IOAA-style prep.",
    topics:["Astrophysics","Celestial Mechanics","Stars","Galaxies","Cosmology","Observational Astronomy","Planetary Science","Space Physics"],
    questionCount:740, competitionCount:6 },
  { slug:"earth-science", name:"Earth Science", short:"Earth", icon:"globe", color:"var(--sub-earth)",
    desc:"Geology, meteorology, oceanography and climate systems for IESO-style prep.",
    topics:["Geology","Meteorology","Oceanography","Environmental Science","Earth Systems","Geophysics","Climate Science"],
    questionCount:520, competitionCount:5 },
  { slug:"engineering", name:"Engineering & Robotics", short:"Eng", icon:"gear", color:"var(--sub-eng)",
    desc:"Electronics, control systems, robotics and applied design for build-based competitions.",
    topics:["Electronics","Mechanical Design","Control Systems","Robotics","Circuits","Sensors","CAD","Automation","Engineering Design"],
    questionCount:410, competitionCount:7 },
  { slug:"ai-data-science", name:"AI & Data Science", short:"AI", icon:"cpu", color:"var(--sub-ai)",
    desc:"Machine learning, statistics and applied data analysis for research-style challenges.",
    topics:["Machine Learning","Data Analysis","Statistics","Computer Vision","NLP","AI Algorithms"],
    questionCount:365, competitionCount:4 },
];

const SOO_COMPETITIONS = [
  { slug:"imo", name:"International Mathematical Olympiad", short:"IMO", subject:"mathematics", organizer:"IMO Board", country:"International", type:"International", format:"Individual", age:"Grades 9–12", difficulty:5, online:false, category:"Exam", regStatus:"Selection ongoing",
    desc:"The oldest and most prestigious international mathematics competition for pre-university students, held annually since 1959.",
    stages:["School round","National olympiad","National team selection","International olympiad"], months:"July", editions:65 },
  { slug:"egmo", name:"European Girls' Mathematical Olympiad", short:"EGMO", subject:"mathematics", organizer:"EGMO Committee", country:"Europe", type:"International", format:"Individual", age:"Grades 9–12", difficulty:5, online:false, category:"Exam", regStatus:"Nominations open",
    desc:"An international mathematical olympiad for girls, designed to encourage participation of young women in competition mathematics.",
    stages:["National selection","International olympiad"], months:"April", editions:14 },
  { slug:"ipho", name:"International Physics Olympiad", short:"IPhO", subject:"physics", organizer:"IPhO Board", country:"International", type:"International", format:"Individual", age:"Secondary school", difficulty:5, online:false, category:"Exam", regStatus:"Selection ongoing",
    desc:"A theoretical and experimental physics competition bringing together the strongest pre-university physicists worldwide.",
    stages:["National olympiad","National camp","International olympiad"], months:"July", editions:55 },
  { slug:"icho", name:"International Chemistry Olympiad", short:"IChO", subject:"chemistry", organizer:"IChO Steering Committee", country:"International", type:"International", format:"Individual", age:"Secondary school", difficulty:5, online:false, category:"Exam", regStatus:"Selection ongoing",
    desc:"A theoretical and practical laboratory examination testing chemistry knowledge at the highest pre-university level.",
    stages:["National selection","National camp","International olympiad"], months:"July", editions:57 },
  { slug:"ibo", name:"International Biology Olympiad", short:"IBO", subject:"biology", organizer:"IBO International Board", country:"International", type:"International", format:"Individual", age:"Secondary school", difficulty:5, online:false, category:"Exam", regStatus:"Selection ongoing",
    desc:"Theoretical and practical biology examinations spanning cell biology, genetics, physiology, ecology and evolution.",
    stages:["National olympiad","National camp","International olympiad"], months:"July", editions:36 },
  { slug:"ioi", name:"International Olympiad in Informatics", short:"IOI", subject:"computer-science", organizer:"IOI Host Country", country:"International", type:"International", format:"Individual", age:"Secondary school", difficulty:5, online:false, category:"Exam", regStatus:"Selection ongoing",
    desc:"The premier competitive programming olympiad, testing algorithmic problem-solving through timed contest submissions.",
    stages:["National selection","Training camp","International olympiad"], months:"August", editions:37 },
  { slug:"ioaa", name:"International Olympiad on Astronomy and Astrophysics", short:"IOAA", subject:"astronomy", organizer:"IOAA Board", country:"International", type:"International", format:"Individual", age:"Secondary school", difficulty:4, online:false, category:"Exam", regStatus:"Selection ongoing",
    desc:"Theoretical, data-analysis and observational rounds covering astrophysics and celestial mechanics.",
    stages:["National selection","International olympiad"], months:"August", editions:18 },
  { slug:"ieso", name:"International Earth Science Olympiad", short:"IESO", subject:"earth-science", organizer:"IESO Board", country:"International", type:"International", format:"Team", age:"Secondary school", difficulty:4, online:false, category:"Exam", regStatus:"Selection ongoing",
    desc:"Earth-system science competition combining written tests, practical exercises and team fieldwork investigations.",
    stages:["National selection","International olympiad"], months:"August", editions:17 },
  { slug:"usamo", name:"USA Mathematical Olympiad", short:"USAMO", subject:"mathematics", organizer:"MAA", country:"United States", type:"National", format:"Individual", age:"Grades 9–12", difficulty:5, online:false, category:"Exam", regStatus:"By qualification (AIME)",
    desc:"A six-problem proof-based exam that determines the US IMO team, reached via AMC and AIME qualification.",
    stages:["AMC","AIME","USAMO","MOP selection"], months:"March", editions:54 },
  { slug:"bpho", name:"British Physics Olympiad", short:"BPhO", subject:"physics", organizer:"BPhO Committee", country:"United Kingdom", type:"National", format:"Individual", age:"Sixth form", difficulty:4, online:false, category:"Exam", regStatus:"Registration open",
    desc:"A national physics competition series used to select the UK team for the International Physics Olympiad.",
    stages:["BPhO Round 1","BPhO Round 2","Camp selection","IPhO team"], months:"November–March", editions:41 },
  { slug:"frc", name:"FIRST Robotics Competition", short:"FRC", subject:"engineering", organizer:"FIRST", country:"International", type:"International", format:"Team", age:"Grades 9–12", difficulty:4, online:false, category:"Robotics", regStatus:"Season open",
    desc:"A season-long build competition where teams design, build and program robots to complete a themed game.",
    stages:["Kickoff","Build season","Regional events","Championship"], months:"January–April", editions:35 },
  { slug:"isef", name:"International Science and Engineering Fair", short:"ISEF", subject:"ai-data-science", organizer:"Society for Science", country:"International", type:"International", format:"Individual/Team", age:"Grades 9–12", difficulty:4, online:false, category:"Research", regStatus:"Affiliated fair qualification",
    desc:"The world's largest pre-college science research competition, spanning every STEM discipline.",
    stages:["School fair","Regional/affiliated fair","ISEF"], months:"May", editions:75 },
  { slug:"nacloly", name:"National Chemistry Olympiad", short:"NChO", subject:"chemistry", organizer:"National Chemical Society", country:"National (varies)", type:"National", format:"Individual", age:"Secondary school", difficulty:4, online:false, category:"Exam", regStatus:"Registration open",
    desc:"A national qualifying exam series feeding into IChO team selection camps.",
    stages:["Local round","National round","Camp selection"], months:"February", editions:29 },
  { slug:"codeforces-global", name:"Codeforces Global Rounds", short:"CF Global", subject:"computer-science", organizer:"Codeforces", country:"Online / Global", type:"International", format:"Individual", age:"Open", difficulty:3, online:true, category:"Coding", regStatus:"Rolling — monthly rounds",
    desc:"Frequent online competitive programming rounds used by olympiad students worldwide for rating-based practice.",
    stages:["Registration","Live round","Rating update"], months:"Monthly", editions:220 },
];

const SOO_QUESTIONS = [
  { id:"MATH-1042", subject:"mathematics", topic:"Number Theory", competition:"imo", year:2023, difficulty:5, points:7, type:"Proof", time:45, solved:38,
    title:"Prove that for positive integers a, b, the expression gcd(a,b)·lcm(a,b) equals a·b, and use it to bound solutions of a Diophantine equation.",
    stem:"Let $a, b$ be positive integers. Prove that $\\gcd(a,b)\\cdot\\mathrm{lcm}(a,b) = ab$, and hence determine all pairs $(a,b)$ with $a+b=48$ and $\\gcd(a,b)=6$.",
    hint:"Write $a=6x$, $b=6y$ with $\\gcd(x,y)=1$ and substitute into the sum condition.",
    solution:"Since $\\gcd(a,b)\\cdot\\mathrm{lcm}(a,b)=ab$ follows from prime-factorisation exponents, write $a=6x,\\,b=6y$ with $\\gcd(x,y)=1$. Then $6x+6y=48 \\Rightarrow x+y=8$ with $\\gcd(x,y)=1$, giving pairs $(1,7),(3,5),(5,3),(7,1)$, so $(a,b)\\in\\{(6,42),(18,30),(30,18),(42,6)\\}$.",
    concepts:["GCD/LCM identity","Diophantine substitution","Coprimality"] },
  { id:"MATH-0871", subject:"mathematics", topic:"Geometry", competition:"egmo", year:2022, difficulty:4, points:6, type:"Proof", time:40, solved:44,
    title:"Show that the diagonals of a cyclic quadrilateral with perpendicular diagonals satisfy a sum-of-squares identity.",
    stem:"Let $ABCD$ be a cyclic quadrilateral whose diagonals meet at right angles at $P$. Prove that $AP^2+BP^2+CP^2+DP^2 = AB^2+CD^2$ is equivalent to a known circle-power identity, and verify it for a specific inscribed square.",
    hint:"Apply the Pythagorean theorem in each of the four right triangles formed at $P$.",
    solution:"Each side satisfies e.g. $AB^2 = AP^2+BP^2$, so summing opposite sides recovers the target identity directly from the four right triangles at $P$.",
    concepts:["Cyclic quadrilaterals","Perpendicular diagonals","Pythagorean decomposition"] },
  { id:"PHYS-2210", subject:"physics", topic:"Mechanics", competition:"ipho", year:2023, difficulty:4, points:10, type:"Numerical", time:35, solved:51,
    title:"A uniform rod pivoted at one end is released from horizontal — find the angular velocity at the vertical position.",
    stem:"A uniform rod of length $L$ and mass $m$ is pivoted at one end and released from rest in the horizontal position. Using energy conservation, find its angular velocity $\\omega$ when it passes through the vertical position.",
    hint:"The moment of inertia of a rod about its end is $\\tfrac{1}{3}mL^2$; equate loss in potential energy to rotational kinetic energy.",
    solution:"Energy conservation gives $mg\\frac{L}{2} = \\frac12\\left(\\frac13 mL^2\\right)\\omega^2$, so $\\omega=\\sqrt{\\dfrac{3g}{L}}$.",
    concepts:["Rotational kinetic energy","Moment of inertia","Energy conservation"] },
  { id:"PHYS-1904", subject:"physics", topic:"Electricity", competition:"bpho", year:2021, difficulty:3, points:8, type:"Numerical", time:25, solved:63,
    title:"Determine the equivalent resistance of a symmetric resistor cube network between two opposite corners.",
    stem:"Twelve equal resistors of resistance $R$ form the edges of a cube. Find the equivalent resistance between two diagonally opposite corners of the cube.",
    hint:"Use the symmetry of current distribution to identify nodes at equal potential.",
    solution:"By symmetry, the equivalent resistance between opposite corners of a resistor cube is $R_{eq}=\\dfrac{5R}{6}$.",
    concepts:["Circuit symmetry","Equivalent resistance","Kirchhoff's laws"] },
  { id:"CHEM-1330", subject:"chemistry", topic:"Chemical Equilibrium", competition:"icho", year:2022, difficulty:4, points:9, type:"Numerical", time:30, solved:47,
    title:"Calculate the equilibrium pH of a buffer after addition of a strong base, using the Henderson–Hasselbalch relation.",
    stem:"A buffer contains 0.30 mol acetic acid ($K_a=1.8\\times10^{-5}$) and 0.20 mol sodium acetate in 1 L. Calculate the pH after 0.05 mol NaOH is added, assuming negligible volume change.",
    hint:"NaOH consumes acetic acid and produces acetate in a 1:1 ratio before applying Henderson–Hasselbalch.",
    solution:"After reaction: acid $=0.25$ mol, acetate $=0.25$ mol. $\\mathrm{pH}=pK_a+\\log(1)=4.74$.",
    concepts:["Buffer chemistry","Henderson–Hasselbalch","Acid–base neutralisation"] },
  { id:"CHEM-0765", subject:"chemistry", topic:"Organic Chemistry", competition:"nacloly", year:2023, difficulty:3, points:6, type:"Multiple Choice", time:15, solved:71,
    title:"Identify the major product of an E2 elimination on a substituted cyclohexane under strong, bulky base conditions.",
    stem:"Which alkene is the major product when 1-bromo-4-tert-butylcyclohexane is treated with potassium tert-butoxide?",
    hint:"A bulky base favours the Hofmann (less substituted) product and anti-periplanar geometry governs which chair conformer reacts.",
    solution:"The bulky base favours the less-hindered, anti-periplanar elimination pathway, giving the Hofmann alkene as the major product.",
    concepts:["E2 elimination","Hofmann vs Zaitsev","Conformational analysis"] },
  { id:"BIO-1587", subject:"biology", topic:"Genetics", competition:"ibo", year:2022, difficulty:4, points:8, type:"Numerical", time:25, solved:55,
    title:"Predict offspring genotype ratios from a dihybrid cross involving linked genes with known recombination frequency.",
    stem:"Two genes are 20 map units apart on the same chromosome. For a dihybrid cross $AaBb \\times aabb$, what fraction of offspring are expected to be recombinant?",
    hint:"Map distance in centimorgans directly gives the percentage of recombinant gametes.",
    solution:"A map distance of 20 cM corresponds to 20% recombinant gametes, so 20% of offspring are recombinant phenotypes.",
    concepts:["Genetic linkage","Recombination frequency","Test cross analysis"] },
  { id:"BIO-0942", subject:"biology", topic:"Cell Biology", competition:"ibo", year:2021, difficulty:3, points:5, type:"Multiple Select", time:12, solved:68,
    title:"Select all organelles directly involved in the secretory pathway of a eukaryotic cell.",
    stem:"Which of the following are part of the classical secretory pathway? (Select all that apply.)",
    hint:"Trace the path a secreted protein takes from synthesis to exocytosis.",
    solution:"Rough ER, Golgi apparatus and secretory vesicles are all part of the secretory pathway; the nucleolus and peroxisome are not.",
    concepts:["Endomembrane system","Protein trafficking","Organelle function"] },
  { id:"CS-2201", subject:"computer-science", topic:"Dynamic Programming", competition:"ioi", year:2023, difficulty:5, points:100, type:"Coding", time:60, solved:22,
    title:"Given a sequence of task durations and deadlines, compute the minimum total lateness using interval DP.",
    stem:"You are given $n$ tasks, each with a duration $d_i$ and deadline $t_i$. Tasks must be scheduled sequentially without overlap. Write a program that outputs the minimum total lateness (sum of max(0, completion − deadline)) across all tasks.",
    hint:"Sort by deadline first — this problem reduces to a classic greedy-with-DP-verification scheduling pattern.",
    solution:"Sorting tasks by deadline and applying an exchange-argument greedy schedule minimises total lateness; verify optimality with a DP over subsets for small $n$ and greedy for large $n$.",
    concepts:["Interval scheduling","Greedy exchange argument","Dynamic programming"] },
  { id:"CS-1765", subject:"computer-science", topic:"Graph Theory", competition:"codeforces-global", year:2024, difficulty:3, points:1900, type:"Coding", time:30, solved:64,
    title:"Determine whether a directed graph contains a cycle using iterative DFS with explicit recursion stack tracking.",
    stem:"Given a directed graph with $n$ nodes and $m$ edges, write a program that determines whether the graph contains a cycle.",
    hint:"Track three states per node: unvisited, in the current DFS stack, and fully processed.",
    solution:"A three-colour DFS (white/grey/black) detects a back edge into a grey node, which certifies a cycle; run DFS from all unvisited nodes.",
    concepts:["Graph traversal","Cycle detection","DFS state tracking"] },
  { id:"ASTRO-0410", subject:"astronomy", topic:"Celestial Mechanics", competition:"ioaa", year:2022, difficulty:4, points:8, type:"Numerical", time:30, solved:41,
    title:"Use Kepler's third law to determine the orbital period of an exoplanet from its semi-major axis and host star mass.",
    stem:"An exoplanet orbits a star of mass $1.2\\,M_\\odot$ at a semi-major axis of $2.0$ AU. Find its orbital period in years.",
    hint:"Kepler's third law in solar units: $T^2 = a^3/M_\\star$ with $T$ in years, $a$ in AU, $M_\\star$ in solar masses.",
    solution:"$T^2 = \\dfrac{a^3}{M_\\star} = \\dfrac{8}{1.2}=6.67 \\Rightarrow T \\approx 2.58$ years.",
    concepts:["Kepler's third law","Orbital dynamics","Unit systems in astronomy"] },
  { id:"EARTH-0212", subject:"earth-science", topic:"Meteorology", competition:"ieso", year:2023, difficulty:3, points:6, type:"Short Answer", time:20, solved:58,
    title:"Explain why the adiabatic lapse rate differs between dry and saturated air parcels.",
    stem:"Explain, using the concept of latent heat release, why the saturated (moist) adiabatic lapse rate is smaller in magnitude than the dry adiabatic lapse rate.",
    hint:"Condensation releases latent heat that partially offsets the cooling due to expansion.",
    solution:"As a saturated parcel rises and cools, water vapour condenses and releases latent heat, which offsets some of the adiabatic cooling — so the moist lapse rate is smaller in magnitude than the dry rate (~9.8°C/km).",
    concepts:["Adiabatic processes","Latent heat","Atmospheric stability"] },
  { id:"ENG-0188", subject:"engineering", topic:"Control Systems", competition:"frc", year:2023, difficulty:3, points:7, type:"Short Answer", time:20, solved:49,
    title:"Design a simple PID control loop for a drivetrain motor targeting a set encoder position.",
    stem:"A robot drivetrain uses a PID controller to reach a target encoder position. Describe the effect of increasing the derivative gain $K_d$ on overshoot and settling time.",
    hint:"Derivative action responds to the rate of change of error, damping oscillation.",
    solution:"Increasing $K_d$ adds damping proportional to the rate of change of error, which typically reduces overshoot and can shorten settling time — until excessive $K_d$ amplifies sensor noise and destabilises the loop.",
    concepts:["PID control","System damping","Sensor noise sensitivity"] },
  { id:"AI-0099", subject:"ai-data-science", topic:"Machine Learning", competition:"isef", year:2023, difficulty:3, points:6, type:"Multiple Choice", time:15, solved:66,
    title:"Identify the effect of increasing regularization strength on model bias and variance.",
    stem:"As the regularization strength $\\lambda$ in ridge regression increases from 0, what typically happens to model bias and variance?",
    hint:"Regularization shrinks coefficients toward zero, simplifying the model.",
    solution:"Increasing $\\lambda$ shrinks coefficients toward zero, which increases bias but decreases variance — a classic bias–variance trade-off.",
    concepts:["Regularization","Bias–variance trade-off","Ridge regression"] },
  { id:"MATH-1188", subject:"mathematics", topic:"Combinatorics", competition:"usamo", year:2022, difficulty:5, points:7, type:"Proof", time:45, solved:29,
    title:"Prove a counting identity for lattice paths avoiding a diagonal using a reflection argument.",
    stem:"Prove that the number of lattice paths from $(0,0)$ to $(n,n)$ using unit right/up steps that never rise above the diagonal $y=x$ is the $n$th Catalan number.",
    hint:"Use the reflection principle: reflect any path that first touches $y=x+1$ across that line.",
    solution:"Reflecting invalid paths at their first touch of $y=x+1$ maps them bijectively onto all paths to $(n-1,n+1)$, giving $\\binom{2n}{n}-\\binom{2n}{n-1}=C_n$ valid paths.",
    concepts:["Reflection principle","Catalan numbers","Bijective counting"] },
  { id:"PHYS-0733", subject:"physics", topic:"Thermodynamics", competition:"ipho", year:2021, difficulty:4, points:9, type:"Numerical", time:30, solved:46,
    title:"Compute the efficiency of a Carnot engine operating between two given reservoir temperatures.",
    stem:"A Carnot engine operates between a hot reservoir at 600 K and a cold reservoir at 300 K. Find its theoretical efficiency, and the work output per cycle if it absorbs 800 J of heat from the hot reservoir.",
    hint:"Carnot efficiency depends only on the ratio of absolute reservoir temperatures.",
    solution:"$\\eta = 1-\\dfrac{T_C}{T_H}=1-\\dfrac{300}{600}=0.5$, so work output $=0.5\\times800\\text{ J}=400$ J.",
    concepts:["Carnot efficiency","Second law of thermodynamics","Heat engines"] },
  { id:"BIO-1120", subject:"biology", topic:"Ecology", competition:"ibo", year:2023, difficulty:3, points:6, type:"Numerical", time:20, solved:60,
    title:"Estimate population size using the Lincoln–Petersen mark-recapture method.",
    stem:"In a mark-recapture study, 40 fish are captured, tagged and released. Later, 50 fish are captured, of which 8 are tagged. Estimate the total population size.",
    hint:"Apply the Lincoln–Petersen estimator: $N \\approx \\dfrac{M \\times C}{R}$.",
    solution:"$N \\approx \\dfrac{40\\times50}{8}=250$ fish.",
    concepts:["Mark-recapture","Population estimation","Sampling assumptions"] },
  { id:"CHEM-1904", subject:"chemistry", topic:"Electrochemistry", competition:"icho", year:2021, difficulty:4, points:8, type:"Numerical", time:25, solved:39,
    title:"Determine cell potential and spontaneity from standard reduction potentials of a galvanic cell.",
    stem:"A galvanic cell is built from $Zn^{2+}/Zn$ ($E^\\circ=-0.76$ V) and $Cu^{2+}/Cu$ ($E^\\circ=+0.34$ V) half-cells. Calculate the standard cell potential and state whether the reaction is spontaneous.",
    hint:"$E^\\circ_{cell} = E^\\circ_{cathode} - E^\\circ_{anode}$, with the more positive potential acting as cathode.",
    solution:"$E^\\circ_{cell} = 0.34-(-0.76)=1.10$ V $>0$, so the reaction is spontaneous under standard conditions.",
    concepts:["Standard reduction potential","Galvanic cells","Spontaneity (ΔG vs E°)"] },
  { id:"CS-1420", subject:"computer-science", topic:"Data Structures", competition:"ioi", year:2022, difficulty:4, points:100, type:"Coding", time:45, solved:33,
    title:"Support range-sum queries and point updates on an array using a Fenwick tree (Binary Indexed Tree).",
    stem:"Implement a data structure that supports point updates and prefix-sum queries on an array of size $n$ in $O(\\log n)$ time each.",
    hint:"A Fenwick tree stores partial sums at indices determined by the lowest set bit.",
    solution:"Maintain an array `bit[]` where `bit[i]` covers a range determined by `i & -i`; update by repeatedly adding `i & -i`, and query by repeatedly subtracting `i & -i`.",
    concepts:["Fenwick tree","Prefix sums","Bit manipulation"] },
];

const SOO_ARTICLES = [
  { slug:"why-timed-practice-matters", title:"Why Timed Practice Changes How You Solve", subject:"mathematics", category:"Exam Strategy", author:"Editorial Team", date:"2026-06-02", readTime:6,
    excerpt:"Working without a clock teaches you to solve problems. Working against one teaches you to finish them — here's how to build that muscle deliberately.",
    body:["Most students first learn a subject untimed: read, think, retry, look things up. That's the right way to build understanding. But an olympiad exam rewards a second, different skill — deciding quickly which of six problems to attack first, and when to abandon a dead end.","Timed practice exposes a gap that untimed practice hides. You may be able to solve a problem in twenty minutes with no pressure, then freeze completely with a clock running. The fix isn't to grind more untimed problems — it's to practice the specific skill of triage under a visible timer, on problems slightly below your ceiling difficulty.","Start with sessions half the length of the real exam, using problems you've mostly seen the topic of. Gradually increase both the difficulty and the fraction of unfamiliar problems as your triage instinct improves."] },
  { slug:"structuring-a-90-day-plan", title:"Structuring a 90-Day Olympiad Preparation Plan", subject:"mathematics", category:"Olympiad Strategy", author:"Editorial Team", date:"2026-05-18", readTime:8,
    excerpt:"Ninety days is enough time to move a full difficulty tier if the plan has three distinct phases instead of one long grind.",
    body:["A common mistake is treating 90 days as one undifferentiated block of practice. It works far better as three phases: a diagnostic and foundations phase (roughly 3 weeks), a topic-depth phase (roughly 6 weeks), and a simulation phase (the final 3 weeks).","In the foundations phase, take one full mock exam cold to identify your weakest two or three topics — resist the urge to skip this because it feels discouraging. The topic-depth phase should allocate roughly 60% of practice time to those weak areas while maintaining light contact with your strengths.","The final simulation phase should almost entirely consist of full timed mock exams under real conditions, with careful post-mortems rather than new content."] },
  { slug:"reading-a-physics-problem", title:"How to Read a Physics Problem Before Solving It", subject:"physics", category:"Problem Solving", author:"Editorial Team", date:"2026-04-30", readTime:5,
    excerpt:"The highest-leverage sixty seconds of any physics problem happen before you write a single equation.",
    body:["Strong problem solvers spend the first minute doing something that looks like nothing: identifying the system, listing what's conserved, and sketching the geometry. Weaker solvers start writing equations from the first sentence, which often locks them into the wrong frame.","Before touching algebra, ask three questions: what quantity is conserved or changing steadily, what does the geometry force to be true, and what limiting case would make the answer obvious. That third question — the limiting case — is one of the most underused checks in physics olympiad problem solving.","Once you have answers to those three questions, the equations you need are usually obvious, and you write far fewer wrong ones."] },
  { slug:"organic-mechanism-patterns", title:"Six Mechanism Patterns That Cover Most Organic Chemistry Problems", subject:"chemistry", category:"Concepts", author:"Editorial Team", date:"2026-04-12", readTime:9,
    excerpt:"Organic chemistry looks infinite until you notice that most olympiad mechanisms are variations on a small number of patterns.",
    body:["Students often treat every organic mechanism as a new thing to memorise. In practice, the overwhelming majority of olympiad-level mechanism questions draw from six recurring patterns: nucleophilic substitution, elimination, electrophilic addition, nucleophilic addition to carbonyls, electrophilic aromatic substitution, and radical chain reactions.","Rather than memorising hundreds of individual reactions, build a one-page reference for each pattern: what makes a good nucleophile or electrophile in that context, what the rate-determining step looks like, and what stereochemical outcome to expect.","When you hit an unfamiliar reaction on an exam, the fastest path to a partial-credit answer is asking which of the six patterns it most resembles, then adapting from there."] },
  { slug:"genetics-crosses-fast", title:"Solving Genetics Crosses Fast Under Time Pressure", subject:"biology", category:"Problem Solving", author:"Editorial Team", date:"2026-03-22", readTime:7,
    excerpt:"Punnett squares work, but they're slow. Here's the shortcut notation top biology olympiad students actually use in-exam.",
    body:["A full Punnett square for a trihybrid cross has 64 cells — nobody draws that under time pressure. Instead, treat each gene independently using the product rule, then multiply probabilities for the specific genotype or phenotype combination you need.","For linked genes, skip the square entirely and reason directly from recombination frequency: a gene pair 12 map units apart produces 12% recombinant gametes, split evenly between the two recombinant classes.","Practicing this notation on twenty short problems is far more valuable before an exam than working three enormous multi-gene Punnett squares by hand."] },
  { slug:"competitive-programming-io", title:"The Most Common IO-Handling Mistakes in Competitive Programming", subject:"computer-science", category:"Programming", author:"Editorial Team", date:"2026-03-05", readTime:6,
    excerpt:"A correct algorithm with a broken input parser still scores zero. Here's what trips up strong programmers under contest pressure.",
    body:["Judges are unforgiving about format. The single most common cause of an unexpected wrong-answer verdict on an otherwise-correct solution is mishandling input format edge cases — trailing whitespace, multiple test cases per file, or unspecified upper bounds on array size.","Before writing any algorithm, write and test your input parser against the exact sample input, including boundary cases like n = 0 or n = 1 explicitly, even if the problem statement seems to imply they won't occur.","Keep a small personal library of tested IO templates for your language of choice — fast IO for C++, buffered readers for Python — and reuse them rather than rewriting boilerplate under time pressure."] },
  { slug:"observational-astronomy-basics", title:"What to Actually Practice for Observational Astronomy Rounds", subject:"astronomy", category:"Exam Strategy", author:"Editorial Team", date:"2026-02-14", readTime:6,
    excerpt:"Observational rounds reward specific, practiced skills — not general astronomy knowledge.",
    body:["Observational astronomy rounds surprise students who prepared only theory, because the skills tested are narrow and mechanical: star-hopping with a planisphere, estimating angular separation by eye, and reading a telescope's setting circles quickly and accurately.","The highest-leverage practice is repetition with real or simulated star charts under a time limit, not additional theoretical reading. Aim to identify twenty bright reference stars and their approximate coordinates from memory.","Practice converting between altitude-azimuth and equatorial coordinates by hand at least until it's automatic — this single skill recovers the most points under exam time pressure."] },
  { slug:"reading-a-weather-map", title:"Reading a Synoptic Weather Map Like an Earth Science Olympiad Judge", subject:"earth-science", category:"Concepts", author:"Editorial Team", date:"2026-01-27", readTime:5,
    excerpt:"A synoptic chart looks dense until you know the four things a judge actually wants you to identify first.",
    body:["Faced with a synoptic weather chart for the first time, most students try to read every isobar and front simultaneously. Judges are usually testing four specific skills: locating pressure systems, identifying front types, estimating wind direction from isobar spacing, and predicting near-term weather change.","Work the chart in that fixed order every time, rather than jumping around. Locate highs and lows first, then trace fronts, then infer wind direction using the geostrophic approximation, and only then attempt a forecast statement.","This fixed sequence turns a dense, intimidating chart into a five-minute mechanical exercise instead of an open-ended reading task."] },
];

const SOO_RESOURCES = [
  { slug:"imo-formula-sheet", title:"Olympiad Geometry Formula Sheet", subject:"mathematics", type:"Formula Sheet", level:"Advanced", year:2026, language:"English", pages:6,
    desc:"A condensed reference covering triangle centers, circle theorems, trigonometric identities and common lemmas used across IMO-style geometry problems." },
  { slug:"ipho-experimental-guide", title:"Experimental Physics Lab Guide", subject:"physics", type:"Lab Guide", level:"Advanced", year:2025, language:"English", pages:24,
    desc:"Uncertainty propagation, curve fitting and apparatus-handling conventions expected in IPhO-style practical exams." },
  { slug:"icho-past-papers-2024", title:"IChO 2024 Official Past Paper Set", subject:"chemistry", type:"Past Paper", level:"Advanced", year:2024, language:"English", pages:38,
    desc:"Complete theoretical and practical examination papers from the 2024 International Chemistry Olympiad, with official marking schemes." },
  { slug:"genetics-cheat-sheet", title:"Classical & Molecular Genetics Cheat Sheet", subject:"biology", type:"Cheat Sheet", level:"Intermediate", year:2026, language:"English", pages:4,
    desc:"One-page reference for Mendelian ratios, linkage mapping, and molecular genetics vocabulary for competition use." },
  { slug:"cp-algorithm-templates", title:"Competitive Programming Algorithm Templates", subject:"computer-science", type:"Reference", level:"Advanced", year:2026, language:"English", pages:19,
    desc:"Tested C++ templates for segment trees, Fenwick trees, graph traversal, and common dynamic-programming patterns." },
  { slug:"astro-coordinate-systems", title:"Coordinate Systems in Observational Astronomy", subject:"astronomy", type:"Study Guide", level:"Intermediate", year:2025, language:"English", pages:9,
    desc:"Working conversions between horizontal, equatorial and ecliptic coordinate systems with worked examples." },
  { slug:"synoptic-map-symbols", title:"Synoptic Map Symbol Reference", subject:"earth-science", type:"Reference", level:"Beginner", year:2025, language:"English", pages:3,
    desc:"Standard WMO symbols for fronts, pressure systems and station models used in earth science olympiad map questions." },
  { slug:"pid-tuning-notes", title:"PID Tuning Field Notes for Robotics Teams", subject:"engineering", type:"Notes", level:"Intermediate", year:2026, language:"English", pages:7,
    desc:"Practical tuning heuristics for drivetrain and arm control loops used by competitive robotics teams." },
  { slug:"ml-competition-starter", title:"Applied ML Competition Starter Kit", subject:"ai-data-science", type:"Reference", level:"Intermediate", year:2026, language:"English", pages:12,
    desc:"Baseline modelling workflow, validation strategy and common pitfalls for data-driven research competitions." },
];

const SOO_ROADMAPS = [
  { slug:"beginner-to-olympiad-math", title:"Beginner to Olympiad — Mathematics", subject:"mathematics", duration:"6 months", level:"Beginner start",
    desc:"A structured path from standard curriculum mathematics to olympiad-level proof writing.",
    milestones:["Master core algebra & number sense","Learn olympiad proof techniques (induction, contradiction, pigeonhole)","Topic-depth: number theory & combinatorics","Topic-depth: geometry & inequalities","Full mock exam cycle","National-level simulation"] },
  { slug:"30-day-sprint", title:"30-Day Pre-Exam Sprint", subject:"mathematics", duration:"30 days", level:"Any level",
    desc:"A short, intense revision cycle for students with an exam already scheduled.",
    milestones:["Diagnostic mock + weak-area report","Days 2–20: targeted weak-topic drilling","Days 21–27: mixed timed practice sets","Days 28–30: full simulations + review"] },
  { slug:"ipho-prep", title:"IPhO Preparation Roadmap", subject:"physics", duration:"Full year", level:"National team candidates",
    desc:"A full preparation cycle from national olympiad qualification through international team training.",
    milestones:["Mechanics & thermodynamics depth","Electromagnetism depth","Modern physics & relativity","Experimental technique bootcamp","Past-paper simulation block","Final team training camp"] },
  { slug:"icho-prep", title:"IChO Preparation Roadmap", subject:"chemistry", duration:"Full year", level:"National team candidates",
    desc:"Theory and practical-lab preparation aligned with the official IChO syllabus.",
    milestones:["General & physical chemistry depth","Organic mechanism mastery","Analytical & spectroscopy training","Practical lab technique bootcamp","Timed theory simulations","Final camp & practical mock exam"] },
  { slug:"ibo-prep", title:"IBO Preparation Roadmap", subject:"biology", duration:"Full year", level:"National team candidates",
    desc:"Coverage of the four core IBO domains with a practical-skills track.",
    milestones:["Cell & molecular biology depth","Genetics & evolution depth","Physiology depth","Ecology & systematics depth","Practical/lab skills bootcamp","Full simulation block"] },
  { slug:"ioi-prep", title:"IOI Preparation Roadmap", subject:"computer-science", duration:"Full year", level:"National team candidates",
    desc:"Algorithmic depth building toward international contest performance.",
    milestones:["Core data structures mastery","Graph algorithms depth","Dynamic programming depth","Advanced topics (flows, geometry, strings)","Weekly rated contest practice","Final contest simulation block"] },
  { slug:"astronomy-prep", title:"Astronomy Olympiad Preparation", subject:"astronomy", duration:"4 months", level:"National level",
    desc:"Theory, data-analysis and observational skill preparation for astronomy competitions.",
    milestones:["Celestial mechanics & astrophysics depth","Data analysis technique training","Observational skill drills","Full simulation rounds"] },
  { slug:"60-day-plan", title:"60-Day Preparation Plan", subject:"mathematics", duration:"60 days", level:"Any level",
    desc:"A balanced middle-length plan between the 30-day sprint and full 90-day cycle.",
    milestones:["Diagnostic + foundations (2 weeks)","Topic-depth practice (5 weeks)","Simulation & review (1 week)"] },
];

const SOO_ACHIEVEMENTS = [
  { id:"first-question", name:"First Question", desc:"Solved your first practice question.", icon:"flag" },
  { id:"ten-questions", name:"10 Questions", desc:"Solved 10 questions across any subject.", icon:"flag" },
  { id:"hundred-questions", name:"100 Questions", desc:"Solved 100 questions — a real body of practice.", icon:"target" },
  { id:"five-hundred", name:"500 Questions", desc:"Solved 500 questions. Serious consistency.", icon:"target" },
  { id:"perfect-test", name:"Perfect Test", desc:"Scored 100% on a full custom test.", icon:"medal" },
  { id:"streak-7", name:"7-Day Streak", desc:"Practiced seven days in a row.", icon:"flame" },
  { id:"streak-30", name:"30-Day Streak", desc:"Practiced thirty days in a row.", icon:"flame" },
  { id:"topic-master", name:"Topic Master", desc:"Reached 90%+ mastery in a topic.", icon:"star" },
  { id:"speed-solver", name:"Speed Solver", desc:"Solved 20 questions under target time.", icon:"bolt" },
  { id:"competition-specialist", name:"Competition Specialist", desc:"Completed a full competition-specific practice set.", icon:"medal" },
  { id:"multi-subject", name:"Multi-Subject Explorer", desc:"Practiced questions across 5+ subjects.", icon:"compass" },
];

const SOO_TESTIMONIALS = [
  { name:"Amara O.", role:"IChO 2025 Gold Medalist", quote:"Weak-area practice found gaps in electrochemistry I didn't know I had, three months before the exam that actually mattered.", subject:"chemistry" },
  { name:"Daniyar K.", role:"National Physics Team, Kazakhstan", quote:"The exam-simulation mode is the closest thing to real IPhO timing pressure I found anywhere online.", subject:"physics" },
  { name:"Priya S.", role:"IOI 2025 Participant", quote:"Having algorithms practice and past IOI problems in one searchable place cut my prep planning time in half.", subject:"computer-science" },
  { name:"Lucas M.", role:"EGMO Camp Trainee", quote:"The topic-mastery chart made it obvious I was avoiding combinatorics. I wasn't avoiding it anymore after that.", subject:"mathematics" },
  { name:"Wren T.", role:"Regional Biology Olympiad Finalist", quote:"Short, targeted articles on exam technique mattered almost as much as the question bank itself.", subject:"biology" },
];

const SOO_LEADERBOARD = [
  { rank:1, name:"quantum_fox", country:"KZ", solved:2318, accuracy:94, subject:"physics" },
  { rank:2, name:"epsilon_delta", country:"RO", solved:2201, accuracy:96, subject:"mathematics" },
  { rank:3, name:"orbital_mango", country:"IN", solved:2140, accuracy:91, subject:"astronomy" },
  { rank:4, name:"titrate_this", country:"SG", solved:2088, accuracy:93, subject:"chemistry" },
  { rank:5, name:"greedy_algo", country:"PL", solved:1975, accuracy:89, subject:"computer-science" },
  { rank:6, name:"cell_cycle_z", country:"BR", solved:1902, accuracy:90, subject:"biology" },
  { rank:7, name:"lagrangian_pt", country:"US", solved:1877, accuracy:88, subject:"physics" },
  { rank:8, name:"prime_hunter_9", country:"VN", solved:1834, accuracy:95, subject:"mathematics" },
  { rank:9, name:"synoptic_sam", country:"CA", solved:1690, accuracy:87, subject:"earth-science" },
  { rank:10, name:"pid_loopz", country:"DE", solved:1602, accuracy:85, subject:"engineering" },
];

const SOO_STATS = { questions:11065, competitions:74, subjects:9, practiceSets:312, resources:9, students:48200 };

/* ---------- Accessors ---------- */
const SOO = {
  subjects: SOO_SUBJECTS,
  competitions: SOO_COMPETITIONS,
  questions: SOO_QUESTIONS,
  articles: SOO_ARTICLES,
  resources: SOO_RESOURCES,
  roadmaps: SOO_ROADMAPS,
  achievements: SOO_ACHIEVEMENTS,
  testimonials: SOO_TESTIMONIALS,
  leaderboard: SOO_LEADERBOARD,
  stats: SOO_STATS,
  subject(slug){ return SOO_SUBJECTS.find(s=>s.slug===slug); },
  competition(slug){ return SOO_COMPETITIONS.find(c=>c.slug===slug); },
  question(id){ return SOO_QUESTIONS.find(q=>q.id===id); },
  article(slug){ return SOO_ARTICLES.find(a=>a.slug===slug); },
  resource(slug){ return SOO_RESOURCES.find(r=>r.slug===slug); },
  roadmap(slug){ return SOO_ROADMAPS.find(r=>r.slug===slug); },
  competitionsBySubject(slug){ return SOO_COMPETITIONS.filter(c=>c.subject===slug); },
  questionsBySubject(slug){ return SOO_QUESTIONS.filter(q=>q.subject===slug); },
  difficultyLabel(n){ return ["","Very Easy","Easy","Medium","Hard","Very Hard"][n] || "Medium"; },
};
